import assert from 'node:assert/strict';
import test from 'node:test';
import {build} from 'esbuild';
const bundled=await build({entryPoints:['web/src/lib/hub-computers.ts'],bundle:true,write:false,platform:'node',format:'esm',plugins:[{name:'transport',setup(b){b.onResolve({filter:/^\.\/transport$/},()=>({path:'transport',namespace:'stub'}));b.onLoad({filter:/.*/,namespace:'stub'},()=>({contents:'export const hubTransport={request:(...args)=>globalThis.__hubTestRequest(...args)}'}));}}]});
const {watchHubResource}=await import(`data:text/javascript;base64,${Buffer.from(bundled.outputFiles[0].text).toString('base64')}`);
// Closing waits on two zero-delay timers, one per shared subscription, so a
// busy runner can put a fixed sleep between them. Wait for the close itself.
const settled=()=>new Promise(r=>setTimeout(()=>setTimeout(r,0),0));
const until=async(done,ms=2000)=>{const end=Date.now()+ms;while(!done()&&Date.now()<end)await new Promise(r=>setTimeout(r,1));};
test('resources share a live channel and independently refresh and lose access',async()=>{
  const sockets=[],reads=[],updates=[],errors=[];
  globalThis.window={location:{origin:'http://localhost'}};
  globalThis.WebSocket=class {constructor(url){this.url=url;sockets.push(this);} close(){this.closed=true;}};
  globalThis.__hubTestRequest=async path=>{reads.push(path);return Response.json({path});};
  const flush=()=>new Promise(r=>setImmediate(r));
  const a=watchHubResource('/a',(v,s)=>updates.push(['a',v,s]),e=>errors.push(e),'/shared/live');
  const b=watchHubResource('/b',(v,s)=>updates.push(['b',v,s]),e=>errors.push(e),'/shared/live');
  await flush();assert.equal(sockets.length,1);assert.deepEqual(reads,['/a','/b']);
  sockets[0].onmessage();await flush();assert.deepEqual(reads,['/a','/b','/a','/b']);
  sockets[0].onclose({code:1008});
  assert.equal(errors.length,2);
  assert.deepEqual(updates.slice(-1)[0],['b',undefined,true]);
  a();await settled();assert.equal(sockets[0].closed,undefined);b();await until(()=>sockets[0].closed);assert.equal(sockets[0].closed,true);
  delete globalThis.window;delete globalThis.WebSocket;delete globalThis.__hubTestRequest;
});
test('watchers of one resource share a read, and the greeting reset is not a change',async()=>{
  const sockets=[],reads=[],updates=[];
  globalThis.window={location:{origin:'http://localhost'}};
  globalThis.WebSocket=class {constructor(url){this.url=url;sockets.push(this);} close(){this.closed=true;}};
  globalThis.__hubTestRequest=async path=>{reads.push(path);return Response.json({path,n:reads.length});};
  const flush=()=>new Promise(r=>setImmediate(r));
  const a=watchHubResource('/c',(v,s)=>updates.push(['a',v?.n,s]),()=>{},'/org/live');
  const b=watchHubResource('/c',(v,s)=>updates.push(['b',v?.n,s]),()=>{},'/org/live');
  await flush();
  assert.deepEqual(reads,['/c'],'Two watchers of one path read it once');
  assert.deepEqual(updates,[['a',1,false],['b',1,false]]);
  sockets[0].onopen();
  sockets[0].onmessage({data:JSON.stringify({kind:'reset'})});await flush();
  assert.deepEqual(reads,['/c'],'The reset every socket opens with is covered by the first read');
  sockets[0].onmessage({data:JSON.stringify({kind:'model-defaults.changed'})});await flush();
  assert.deepEqual(reads,['/c','/c'],'A later message reads again');
  const c=watchHubResource('/c',(v,s)=>updates.push(['c',v?.n,s]),()=>{},'/org/live');
  await flush();
  assert.deepEqual(reads,['/c','/c'],'A late watcher is handed the value in hand');
  assert.deepEqual(updates.at(-1),['c',2,false]);
  const d=watchHubResource('/d',()=>{},()=>{},'/org/live');
  await flush();
  assert.deepEqual(reads,['/c','/c','/d'],'Joining an open channel replays open, not the last message');
  a();b();c();d();await until(()=>sockets[0].closed);assert.equal(sockets[0].closed,true);
  delete globalThis.window;delete globalThis.WebSocket;delete globalThis.__hubTestRequest;
});
