import assert from "node:assert/strict";
import { chromium } from "playwright-core";
import { chromiumPath } from "./chromium.mjs";
import { readFileSync, mkdirSync } from "node:fs";
const info = JSON.parse(readFileSync(process.env.QA_SESSION, "utf8"));
const out = process.env.QA_ARTIFACTS ?? "/tmp/remy-pr-artifacts/wrk-13"; mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ executablePath: chromiumPath() });
const until = async (f, message) => { for (let i = 0; i < 150; i++) { if (await f()) return; await new Promise((r) => setTimeout(r, 100)); } throw Error(message); };
const signin = async (email) => {
  const c = await browser.newContext({ viewport: { width: 1280, height: 900 }, colorScheme: "dark" }); const p = await c.newPage();
  await p.goto(info.hubUrl); await p.getByLabel("Email", { exact: true }).fill(email); await p.getByRole("button", { name: "Email sign-in link" }).click();
  await p.getByText("Check your email for your sign-in link.", { exact: true }).waitFor();
  const mail = await (await fetch(`${info.controlUrl}/mail?email=${encodeURIComponent(email)}`, { headers: { authorization: `Bearer ${info.controlToken}` } })).json(); assert.ok(mail.url);
  await p.goto(mail.url); await p.getByRole("button", { name: "Sign out", exact: true }).waitFor();
  assert.ok((await c.cookies()).find((cookie) => cookie.name === "remy_session")?.httpOnly);
  return { c, p };
};
const ada = await signin("ada@example.test"); const grace = await signin("grace@example.test");
const errors = [];
ada.p.on("pageerror", (e) => errors.push(e.message)); grace.p.on("pageerror", (e) => errors.push(e.message));
const nav = (p, label) => p.getByRole("button", { name: label, exact: true }).first().click();
const request = (p, path, method = "GET", body) => p.evaluate(async ({ path, method, body }) => { const r = await fetch(path, { method, headers: { "content-type": "application/json" }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) }); return { status: r.status, body: r.status === 204 ? null : await r.json() }; }, { path, method, body });
await nav(ada.p, "Create organization"); await ada.p.getByLabel("Name", { exact: true }).fill("Studio team"); await ada.p.getByRole("dialog").getByRole("button", { name: "Create organization" }).click();
await until(async () => new URL(ada.p.url().replace("#/", "")).searchParams.has("organization"), "The organization did not open");
const org = new URL(ada.p.url().replace("#/", "")).searchParams.get("organization"); assert.ok(org); const base = `/api/organizations/${org}`;
await nav(ada.p, "Members"); await nav(ada.p, "Invite member"); await ada.p.getByLabel("Email (optional)").fill("grace@example.test"); await nav(ada.p, "Send invitation");
await ada.p.getByText("Your invitation is sent.", { exact: true }).waitFor();
const invitation = (await (await fetch(`${info.controlUrl}/mail?email=grace%40example.test`, { headers: { authorization: `Bearer ${info.controlToken}` } })).json()).url;
await grace.p.goto(invitation); await nav(grace.p, "Accept invitation"); await grace.p.getByRole("button", { name: "Threads", exact: true }).first().waitFor();
// Auth codes and invitation links stay outside the evidence recording.
const a = await browser.newContext({ viewport: { width: 1280, height: 900 }, colorScheme: "dark", storageState: await ada.c.storageState(), recordVideo: { dir: out, size: { width: 1280, height: 900 } } });
const p = await a.newPage(); p.on("pageerror", (e) => errors.push(e.message)); await p.goto(`${info.hubUrl}/#/threads?organization=${org}`);
try {
  await grace.p.getByRole("button", { name: "Prepare the studio release", exact: true }).waitFor();
  // Every member reaches every workspace in the organization; there is no per-workspace restriction.
  const workspace = (await request(p, `${base}/workspaces`, "POST", { name: "Android", origin: "https://example.test/studio/android.git" })).body; assert.equal("restricted" in workspace, false);
  await until(async () => (await request(grace.p, `${base}/workspaces`)).body.workspaces.length === 1, "A member did not see the organization's workspace");
  await nav(p, "Teams"); await nav(p, "Create team"); await p.getByLabel("Name", { exact: true }).fill("Release reviewers"); await p.getByRole("checkbox", { name: "Grace", exact: true }).check(); await nav(p, "Save changes"); await p.getByRole("dialog").waitFor({ state: "hidden" });
  const team = (await request(p, `${base}/teams`)).body.teams[0]; assert.deepEqual((await request(p, `${base}/teams/${team.id}/members`)).body.userIds, ["grace"]);
  await nav(p, "Members"); await p.getByLabel("Role for Grace").click(); await p.getByRole("option", { name: "Admin", exact: true }).click();
  await until(async () => (await request(p, `${base}/members`)).body.members.find((m) => m.userId === "grace").role === "admin", "Role did not persist");
  await p.getByLabel("Role for Grace").click(); await p.getByRole("option", { name: "Member", exact: true }).click();
  await nav(p, "Threads"); await p.screenshot({ path: `${out}/computer-needed.png` });
  await nav(p, "Computers"); await p.getByText("No computers yet", { exact: true }).waitFor();
  await p.getByRole("combobox", { name: "Organization", exact: true }).first().click(); await p.getByRole("option", { name: "Release team", exact: true }).click();
  await p.getByRole("region", { name: "Team threads" }).waitFor();
  await nav(p, "Members"); assert.ok(await p.locator('[data-slot="sidebar-content"]').getByText("Threads", { exact: true }).count());
  await p.reload(); assert.equal(new URL(p.url()).hash.includes("release-team"), true);
  await p.getByRole("combobox", { name: "Organization", exact: true }).first().click(); await p.getByRole("option", { name: "Studio team", exact: true }).click();
  await nav(p, "Threads"); await p.setViewportSize({ width: 390, height: 844 }); await p.waitForTimeout(300); assert.ok(await p.locator('main').first().evaluate((e) => e.scrollWidth <= e.clientWidth)); await p.screenshot({ path: `${out}/mobile-threads.png` });
  await p.setViewportSize({ width: 1280, height: 900 });
  await p.getByRole("combobox", { name: "Organization", exact: true }).first().click(); await p.keyboard.press("Escape"); assert.ok(p.url().includes(org));
  await nav(p, "Teams"); await nav(p, "Remove"); await p.getByRole("alertdialog").getByRole("button", { name: "Cancel", exact: true }).click();
  assert.equal((await request(p, `${base}/teams`)).body.teams.length, 1);
  await nav(p, "Remove"); await p.getByRole("alertdialog").getByRole("button", { name: "Remove", exact: true }).click(); await p.getByRole("alertdialog").waitFor({ state: "hidden" });
  assert.equal((await request(p, `${base}/teams`)).body.teams.length, 0);
  await p.goto(`${info.hubUrl}/workspaces/${workspace.id}?organization=${org}`); await nav(p, "Remove workspace"); await p.getByRole("alertdialog").getByRole("button", { name: "Remove workspace", exact: true }).click(); await p.getByRole("alertdialog").waitFor({ state: "hidden" });
  assert.equal((await request(p, `${base}/workspaces`)).body.workspaces.length, 0);
  await nav(p, "Members"); await nav(p, "Remove"); await p.getByRole("alertdialog").getByRole("button", { name: "Remove", exact: true }).click(); await p.getByRole("alertdialog").waitFor({ state: "hidden" });
  assert.equal((await request(grace.p, `${base}/workspaces`)).status, 404);
  await nav(p, "Sign out"); await p.getByRole("button", { name: "Email sign-in link", exact: true }).waitFor();
  assert.deepEqual(errors, []); console.log("PASS: real magic-link sessions, create organization, invite acceptance, shared workspaces, teams, roles, org switching, persistent sidebar and mobile layout");
} finally { await a.close(); await ada.c.close(); await grace.c.close(); await browser.close(); }
console.log(`VIDEO=${await p.video().path()}`);
