import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync, readdirSync } from "node:fs";
import { sqliteD1 } from "../test/sqlite-d1.js";
import { modelDefaults } from "./model-defaults.js";
test("personal defaults inherit across organizations, override per workspace, and isolate members", async()=>{
 const folder=new URL('../migrations/',import.meta.url);
 const {db,sqlite}=sqliteD1(readdirSync(folder).filter(f=>f.endsWith('.sql')).sort().map(f=>readFileSync(new URL(f,folder),'utf8')).join('\n'));
 sqlite.exec("INSERT INTO user(id,name,email,createdAt,updatedAt) VALUES('ada','Ada','ada@example.test',1,1),('grace','Grace','grace@example.test',1,1); INSERT INTO organizations(id,name,createdAt,updatedAt) VALUES('org','Org',1,1),('other','Other',1,1); INSERT INTO memberships(id,organization_id,user_id,role,createdAt,updatedAt) VALUES('a','org','ada','owner',1,1),('b','org','grace','member',1,1),('c','other','ada','owner',1,1); INSERT INTO organization_workspaces(id,organization_id,name,origin,restricted,created_at,updated_at) VALUES('repo','org','Repo','github.com/sample/repo',1,1,1);");
 const call=async(user='ada',workspace='',choice?:unknown,org='org',computer='')=>modelDefaults(db,org,user,new Request(`https://hub.example/api/organizations/${org}/model-defaults?${new URLSearchParams({...workspace?{workspace}:{},...computer?{computer}:{}})}`,{method:choice===undefined?'GET':'PATCH',...(choice===undefined?{}:{body:JSON.stringify({choice})})}));
 try {
  const remy={provider:'openrouter',model:'openrouter/auto',effort:''};
  assert.equal((await call('ada','',remy)).status,200);
  assert.deepEqual((await (await call('ada','',undefined,'other')).json() as any).remy,remy);
  assert.equal((await (await call('grace')).json() as any).remy,null);
  assert.equal((await (await call('ada','repo')).json() as any).workspace,null);
  const override={provider:'openai',model:'gpt-5',effort:''};
  assert.deepEqual((await (await call('ada','repo',override)).json() as any).workspace,override);
  await call('ada','',{...remy,model:'changed'});
  assert.deepEqual((await (await call('ada','repo')).json() as any).workspace,override);
  await call('ada','repo',null);
  const inherited=await (await call('ada','repo')).json() as any;
  assert.equal(inherited.workspace,null);assert.equal(inherited.remy.model,'changed');
  await assert.rejects(call('grace','repo',override));
  await assert.rejects(call('ada','repo',override,'other'));
  assert.equal((await call('ada','',{provider:'default',model:''})).status,400);
  await call('ada','repo',override);
  const computerChoice={provider:'openrouter',model:'computer/model',effort:''};
  assert.equal((await call('ada','',computerChoice,'org','cloud:fly-sprites')).status,200);
  const combined=await (await call('ada','repo',undefined,'org','cloud:fly-sprites')).json() as any;
  assert.deepEqual(combined.workspace,override);assert.deepEqual(combined.computer,computerChoice);
  assert.equal((await (await call('grace','',undefined,'org','cloud:fly-sprites')).json() as any).computer,null);
  assert.equal((await (await call('ada','',undefined,'other','cloud:fly-sprites')).json() as any).computer,null);
  await assert.rejects(call('ada','',computerChoice,'org','cloud:unknown'));
  assert.equal((await call('ada','repo',computerChoice,'org','cloud:fly-sprites')).status,400);
  await call('ada','',null,'org','cloud:fly-sprites');
  assert.equal((await (await call('ada','',undefined,'org','cloud:fly-sprites')).json() as any).computer,null);
  const {ComputerService}=await import('./computers.js');const {D1ComputerStore}=await import('./computer-store.js');const {D1OrganizationStore}=await import('./organization-store.js');
  const computerId='b7ebfcbe-f2f4-4a1b-8707-3029fa65d14b';
  await new ComputerService(new D1ComputerStore(db),Date.now,'0.1.0',new D1OrganizationStore(db)).register('org','ada',{computerId,name:'Mac',icon:'laptop',platform:'darwin',daemonVersion:'1.0.0',protocol:{minimum:1,maximum:1},publicKey:'k'.repeat(44),capabilities:{providers:[],workspaces:[],worktrees:true,terminals:true,emulator:false}});
  await call('ada','',computerChoice,'org',computerId);
  await assert.rejects(call('grace','',computerChoice,'org',computerId));
  sqlite.exec(`DELETE FROM organization_computers WHERE id='${computerId}'`);
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS count FROM member_computer_model_defaults').get()?.count,0);
  await call('ada','',computerChoice,'org','cloud:fly-sprites');
  sqlite.exec("DELETE FROM organization_workspaces WHERE id='repo'");
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS count FROM member_workspace_model_defaults').get()?.count,0);
  sqlite.exec("DELETE FROM user WHERE id='ada'");
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS count FROM member_model_defaults').get()?.count,0);
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS count FROM member_computer_model_defaults').get()?.count,0);
 } finally {sqlite.close();}
});
