/// What changed, grouped by the day it landed, newest day first. Add an
/// entry to its day's group, creating that group at the top when it is the
/// first change of the day. `backticks` mark inline code.
export const CHANGELOG: { date: string; entries: string[] }[] = [
  { date: "2026-10-02", entries: [
    "Unreleased: Check out pull requests on cloud computers when Git compresses the history request.",
    "Unreleased: Start pull request reviews on cloud computers with your personal model access, including in organizations.",
    "Unreleased: Open review agents in their own tabs beside pull requests, with findings and rules in the review tab and ordinary threads in the sidebar.",
    "Unreleased: Scroll back to your first message in long threads, even after hundreds of tool calls or a computer restart.",
  ] },
  { date: "2026-09-30", entries: [
    "Unreleased: Review agents suggest reusable rules from PR comments, with links to the feedback and your approval before saving.",
    "Unreleased: Let threads delegate work with inherited settings and exchange messages that link to the sending agent.",
    "Keep file headers compact and open the file list as an overlay in narrow PR panes.",
    "Browse PR commits and choose which commits to inspect in Files.",
    "Review agents write their findings directly in the thread.",
    "Keep thread composer controls aligned in narrow splits and on phones.",
    "Skip notification toasts for the thread you are already viewing, including in a split.",
    "Reconnect Claude Code on a Mac without threads continuing to use an expired login.",
    "Open the affected computer’s sign-in settings directly from a thread when its provider session expires.",
    "Choose the review agent’s permission mode when you start it, and keep the pull request beside its new or existing review thread in a split tab.",
    "Open threads, pull requests, workspaces, and settings in one tab strip, then use a tab’s menu or drag its header to split your view, see joined tab headers, and resize the panes.",
    "Keep pull request headers compact in narrow splits, with shorter breadcrumbs and icon controls.",
    "See what each pull request is waiting on from its coloured icon in Pull requests.",
    "Watch the videos in a pull request’s description, including from a private repository.",
    "Read the whole thread on the web, and jump to a message from the marks beside it.",
    "Start a thread on a new computer. Remy creates its environment key, including when the keychain cannot ask you to approve it.",
  ] },
  { date: "2026-09-29", entries: [
    "Choose permissions before starting a thread, or change them in its reply composer for your next message.",
    "Read formatted messages and approval explanations, with commands kept as literal text.",
    "Keep your first message through a temporary startup error, even when the thread appears before delivery finishes.",
    "See your saved avatar beside the workspace environment values you added.",
    "Keep several tabs open in a web thread, add one with +, and go back to your threads.",
    "See a thread you already had open as soon as you refresh.",
    "Keep a new Fly.io computer awake until it joins Remy, and show the startup error when it cannot.",
  ] },
  { date: "2026-09-28", entries: [
    "See every computer, cloud key, and model connection available to you in one Computers list. Edit what you own there; organization-enrolled resources stay read-only.",
    "Use any of your own model keys in organization threads without enrolling it. Enroll an exact named key in Organizations → Computers and models when everyone should be able to choose it.",
    "Sign in to ChatGPT once in Personal model access, then pick ChatGPT in any organization you belong to. Your subscription stays personal and cannot be enrolled for other members.",
    "See temporary connection errors clear as soon as your threads reconnect.",
    "Send long thread messages in any language without their encoded size stopping them early.",
    "Enroll a connected computer or exact named cloud key so everyone in an organization can use it. You can still use your own resources there without enrolling them.",
    "Choose compute placement and model credentials independently, including an employee's own model key on an organization-provided cloud computer.",
    "Reload or reopen Remy while a thread starts, and the same thread continues without losing your first message.",
    "Follow a new thread through branch preparation and message delivery after its computer connects.",
    "See your thread’s workspace icon as soon as you send its first message.",
    "Start your next Fly.io thread from a prepared computer in the same workspace.",
    "Keep the reasoning level you chose while a new cloud thread starts.",
    "Use repository and connector tools from cloud Codex threads.",
    "Connect Linear with a personal API key when OAuth is unavailable.",
    "See one row for each cloud provider and one for Model access in Computers, then open it to manage named keys and organization availability.",
    "Archive or delete a web thread immediately, without waiting for its sleeping cloud computer to wake.",
    "Start a private or shared organization thread on an exact Fly.io key enrolled in that organization, using your own model connection or an exact model key enrolled there.",
    "Choose cloud placement and a model connection independently when you start a thread.",
    "Keep the model, computer, and branch pickers available when a saved cloud choice moves to a named key.",
  ] },
  { date: "2026-09-27", entries: [
    "Add variables and secrets to a workspace from its page, or paste a .env file. Workspace values reach every thread there, and Personal values follow you into every thread you start. Settings → Environments and named environments are gone.",
    "Plan your work in Linear: Tasks and Linear ticket sync are gone from Remy. Connect your own Linear account in Settings → Connections, and your threads keep using Linear.",
    "Use Remy on the web for every computer. The browser window that talked to one computer’s own Remy, and pairing computers over Tailscale, are gone; connect each computer to your account with `remy login` instead.",
    "Choose a model right beside where you opened it, with a tab for your favorites and each connected provider, or search them all at once.",
    "See each model by its name, such as Sonnet 5, and what Default uses, when you pick from your own computer.",
    "Manage GitHub and Linear in one block each, add more accounts with `+`, and make each connection available everywhere or only to one organization.",
    "Work in a smaller Remy: threads, workspaces, and computers. Agents and Routing are gone, and you choose which computer a new thread runs on.",
    "Sign a Mac or Linux machine in with the Remy CLI: choose Connect a computer in Computers and run `remy login` on that machine, then `remy start`. Its page opens when it signs in.",
    "Sign Claude Code or Codex in on a computer you connected, or give it an Anthropic, OpenAI, or Cursor API key instead, from one row per provider on its page.",
    "Pick ChatGPT as a cloud provider's default model when you're signed in, and see only the models your account can run there. A default you haven't set says No default instead of wearing Claude's mark.",
    "Scan Workspaces as one list, newest thread first, with each repository, its owner in All, and when it last ran a thread. Press `/` to search by name, repository or owner, and start a thread in a workspace from its row.",
    "Open a workspace to see its repository, default branch and owner, start a thread in it, or remove it. Everyone in an organization can use all of its workspaces, and you choose each thread’s model in the composer or as your default for a computer; per-workspace access lists and default models are gone.",
    "See your workspaces as soon as you come back to Workspaces, and shimmering rows the first time they load.",
    "Open a pull request to its summary: squash and merge it, request reviewers, mark it ready or back to draft, see how long each check took and which stacked pull requests conflict, and send failing checks to the thread working on its branch.",
    "Review a pull request's files in Remy: mark each file read the way GitHub does, see the exact words that changed, choose lines to comment on GitHub now, add to your pending review, or send to the thread working on the branch, reply to review conversations, and finish your review with Comment, Approve or Request changes.",
    "Follow a pull request in its Activity: reviews, comments, check results and what the thread on its branch is doing, newest last, with a count of what is new since you last looked. Comment on GitHub from there, or send it to the thread working on the branch.",
    "Review a pull request with a review agent: it runs on a computer you choose, checks out the change, marks what to look at beside the diff, and never posts to GitHub. Add a finding to your pending review, dismiss it, or flag it, and save the rules it learns from your corrections for one workspace or all of them. Only you see your rules. When new commits arrive, Review new changes covers just those.",
    "See the Linear issue a pull request belongs to beside its description, found with your own Linear account.",
    "Read Pull requests under one title on the web, matching the Mac app.",
    "Connect Linear for yourself in any organization without an administrator sharing or configuring your account.",
    "Choose All in the account switcher to browse one combined list of personal and organization threads, workspaces, computers, environments, and connections. Choose one account to narrow that same view. New threads open directly in the composer; their workspace chooses the owning account, and Private or Shared stays in the composer. Manage members, computers, cloud keys, and model keys in Organizations, with an explicit organization selector. Enroll exact Personal resources for everyone without exposing their credentials.",
    "Run cloud threads on separate computers with a concurrency limit, and reuse environment values across local and cloud workspaces.",
  ] },
  { date: "2026-09-26", entries: [
    "Install the Remy CLI with `npm i -g @padamchopra/remy`, and run `remy update` to get the latest published version.",
    "Remy is a web app. The iPhone app is no longer part of a release; open Remy in your phone’s browser instead.",
    "See a computer you own in an organization thread’s picker even when that computer is not shared with the organization.",
    "Start web threads with a concrete computer or cloud provider already selected, using the computer you last chose for that workspace until you pick another.",
    "Explore worktrees and reviewing changes.",
  ] },
  { date: "2026-09-25", entries: [
    "Remy is a web app you open in a browser. The Mac app is no longer part of a release; use the Remy CLI on the computers that hold your repositories.",
    "See every composer control on a phone, including the model, computer, sharing, and branch.",
    "Pick Claude Opus 5.5 when Claude Code or Anthropic is on, even if OpenRouter is already selected.",
    "See the same workspace icon in the list and in workspace details.",
    "See each pull request’s workspace icon and name on the tile.",
    "See a workspace’s set icon on a pull request tile without a folder flashing first.",
    "Read each pull request title across the rest of the row.",
    "See stacked pull requests grouped together in the list.",
    "Filter Pull requests to Yours or Review requested.",
    "Read a pull request’s description and comments as markdown, without GitHub comment markers.",
    "See pull request checks grouped by status.",
    "Open hosted Pull requests from the list you already loaded while it refreshes, and see only pull requests that belong to a workspace, including ones you added with a personal access token.",
  ] },
  { date: "2026-09-24", entries: [
    "See a workspace image fill its settings icon, edge to edge.",
    "Open Settings to General, and keep Settings off the sidebar while you are there.",
    "Save named Fly.io Sprites, Modal, or Cursor Cloud keys in Cloud; provider credentials stay outside your computers.",
    "Open Settings from the bottom of the sidebar to General, with a dedicated settings menu and Back to return to your work.",
    "Open Computers to manage computers, with Cloud first, or choose Connected to see and add your computers.",
    "Save named provider keys, keep them when disabled, and choose a provider and model for each cloud thread.",
  ] },
  { date: "2026-09-21", entries: [
    "Read the thread list the same way on the web and on your Mac: one sidebar, threads newest first with pinned ones above them, and the workspace, computer, model and who can see each thread as icons. Hover a row for the rest, and for Archive on a thread that has finished.",
    "Drag the sidebar’s edge to the width you want, on the web and on your Mac. Each device remembers yours, and a double-click puts it back.",
  ] },
  { date: "2026-09-20", entries: [
    "Search your repositories when you add a workspace, with each one’s description, language and last push in the row, and the ones you already added marked.",
    "Use a personal access token to reach repositories in an organization that has not installed Remy, even when GitHub is already connected.",
    "Open Add a workspace to your repositories straight away: the list is read alongside your account rather than after it, and reopening paints the repositories you saw last while it refreshes.",
  ] },
  { date: "2026-09-19", entries: [
    "Run a web thread on Cursor Cloud from Computers, with your Cursor API key and Cloud · Cursor in the picker.",
    "Configure Fly.io Sprites, Modal, and Cursor Cloud independently, and keep your selected cloud computer after refresh.",
  ] },
  { date: "2026-09-18", entries: [
    "See what a new web thread is doing as it starts, including waking or restoring a cloud computer.",
    "See a toast when you invite someone or save settings, instead of a line of status text.",
    "Create a web account with your email and password, then sign in with that password or a sign-in link.",
    "Right-click a thread in the web sidebar to pin, rename, archive, or delete it, including when that cloud computer is idle.",
    "Open a web thread from an address that names only that thread.",
  ] },
  { date: "2026-09-17", entries: [
    "Pick a model in a new web thread from the full provider list, and keep the computer, model, and branch still while they load.",
    "Open a workspace from All and keep its details visible after a refresh. Start a thread from its composer while the sidebar keeps existing threads close.",
    "Choose your web profile avatar from the same presets, photo upload, and GitHub picture picker as the Mac app, and see each member’s saved avatar in organization settings.",
  ] },
  { date: "2026-09-16", entries: [
    "Reply on the web with the shared Mac composer, including inline image attachments and compact send and stop controls.",
    "Recognize providers and participants by their avatars, read consistent sidebar thread rows, and keep the working branch visible in web threads.",
    "Read web threads beneath the same compact tab header as the Mac app, with sharing and computer details in a menu.",
    "Open hosted threads immediately while your cloud computer starts, and retry startup failures without losing your message.",
    "Keep Fly.io computers connected while your threads run, and recover safely after a failed start.",
    "Keep hosted previews connected on slower networks and see a clear message when a connection fails.",
    "Customize hosted workspace icons and colors, and see connected computers and cloud availability.",
    "Choose a GitHub repository when adding a workspace, using your GitHub account or a personal access token.",
    "Choose the starting branch in the web composer with the same branch picker as the Mac app.",
    "Start web threads with your workspace model preference, then your selected computer’s default, then your account default.",
    "Star models in the web picker and keep favorites across visits.",
    "Keep a steady loading indicator while your hosted threads open, with consistent empty states across hosted screens.",
  ] },
  { date: "2026-09-15", entries: [
    "Try local web changes with your live account through an explicit preview approval on your Mac.",
    "Collapse the web sidebar to an icon rail using its own toggle, with labels on hover.",
    "Set up a computer before adding your first web workspace, with guidance when your computer is unavailable.",
  ] },
  { date: "2026-09-14", entries: [
    "Keep your Mac app and its background connection on the same version after updates; older installations need a one-time Mac restart.",
    "Create an account or sign in with an email link, without Google or GitHub.",
    "Sign in with a clearer form, recognizable provider icons, and more room on smaller screens.",
  ] },
  { date: "2026-09-11", entries: [
    "Follow clearer web setup actions, review who invited you before joining, and start your first thread with a request instead of a name.",
  ] },
  { date: "2026-09-10", entries: [
    "Use Remy on the web with a personal account, an optional organization, and a compact sidebar that keeps your threads close.",
  ] },
  { date: "2026-09-09", entries: [
    "Select sample threads and try the composer.",
    "Open the web app and find setup instructions for hosted computers, your Mac, and other devices.",
    "Explore the website’s interactive demo, powered by the same interface components as the app. Browse the setup guides and connect your own computers.",
  ] },
];
